AUTO_OBJECTS += $(PROJECT_PATH)/header.bin
#AUTO_OBJECTS += $(PROJECT_PATH)/stack.bin

AUTO_OBJECTS += $(PROJECT_PATH)/boot.bin
AUTO_OBJECTS += $(PROJECT_PATH)/a20.bin
AUTO_OBJECTS += $(PROJECT_PATH)/nmi.bin
AUTO_OBJECTS += $(PROJECT_PATH)/gdt.bin
AUTO_OBJECTS += $(PROJECT_PATH)/pm.bin
AUTO_OBJECTS += $(PROJECT_PATH)/interrupt.bin

AUTO_OBJECTS += $(PROJECT_PATH)/interrupt.o
AUTO_OBJECTS += $(PROJECT_PATH)/main.o
