ROOT ?= ../..
SHARED ?= $(ROOT)/shared

SHARED_LIBK ?= $(SHARED)/libk
include $(SHARED_LIBK)/library.mk

include $(SHARED)/make/object.mk
SHARED_KERNEL ?= $(SHARED)/kernel
SHARED_KERNEL_INCLUDE ?= $(SHARED_KERNEL)/include
SHARED_KERNEL_NASM_FLAGS ?= -i $(SHARED_KERNEL_INCLUDE) $(SHARED_LIBK_NASM_FLAGS)
SHARED_KERNEL_NASM_OBJECTS ?= $(call object_prepare_nasm,$(SHARED_KERNEL_INCLUDE),$(SHARED_LIBK_NASM_OBJECTS))
SHARED_KERNEL_GCC_FLAGS ?= -I $(SHARED_KERNEL_INCLUDE) $(SHARED_LIBK_GCC_FLAGS)
SHARED_KERNEL_C_OBJECTS ?= $(call object_prepare_c,$(SHARED_KERNEL_INCLUDE),$(SHARED_LIBK_C_OBJECTS))
SHARED_KERNEL_LD_FLAGS ?= $(SHARED_LIBK_LD_FLAGS)
