ROOT ?= ../..
SHARED ?= $(ROOT)/shared

SHARED_LIBEFI ?= $(SHARED)/libefi
include $(SHARED_LIBEFI)/library.mk

include $(SHARED)/make/object.mk
SHARED_BOOTEFI ?= $(SHARED)/bootefi
SHARED_BOOTEFI_INCLUDE ?= $(SHARED_BOOTEFI)/include
SHARED_BOOTEFI_NASM_FLAGS ?= -i $(SHARED_BOOTEFI_INCLUDE) $(SHARED_LIBEFI_NASM_FLAGS)
SHARED_BOOTEFI_NASM_OBJECTS ?= $(call object_prepare_nasm,$(SHARED_BOOTEFI_INCLUDE),$(SHARED_LIBEFI_NASM_OBJECTS))
SHARED_BOOTEFI_GCC_FLAGS ?= -I $(SHARED_BOOTEFI_INCLUDE) $(SHARED_LIBEFI_GCC_FLAGS)
SHARED_BOOTEFI_C_OBJECTS ?= $(call object_prepare_c,$(SHARED_BOOTEFI_INCLUDE),$(SHARED_LIBEFI_C_OBJECTS))
SHARED_BOOTEFI_LD_FLAGS ?= $(SHARED_LIBEFI_LD_FLAGS)
