STAGE1_NAME := stage1
STAGE1_PATH := .
STAGE1_ASFLAGS := -D STAGE1_DEFINED -f bin
STAGE1_OBJECT = $(STAGE1_PATH)/start.nasm
STAGE1_OUTPUT := $(STAGE1_PATH)/$(STAGE1_NAME).img

ASFLAGS += $(STAGE1_ASFLAGS)
OBJECT += $(STAGE1_OBJECT)
