ROOT ?= ../..
SHARED ?= $(ROOT)/shared

SHARED_LIBX ?= $(SHARED)/libx
include $(SHARED_LIBX)/library.mk

include $(SHARED)/make/object.mk
SHARED_LIBB ?= $(SHARED)/libb
SHARED_LIBB_INCLUDE ?= $(SHARED_LIBB)/include
SHARED_LIBB_NASM_FLAGS ?= -i $(SHARED_LIBB_INCLUDE) $(SHARED_LIBX_NASM_FLAGS)
SHARED_LIBB_NASM_OBJECTS ?= $(call object_prepare_nasm,$(SHARED_LIBB_INCLUDE),$(SHARED_LIBX_NASM_OBJECTS))
SHARED_LIBB_GCC_FLAGS ?= -I $(SHARED_LIBB_INCLUDE) $(SHARED_LIBX_GCC_FLAGS)
SHARED_LIBB_C_OBJECTS ?= $(call object_prepare_c,$(SHARED_LIBB_INCLUDE),$(SHARED_LIBX_C_OBJECTS))
SHARED_LIBB_LD_FLAGS ?= $(SHARED_LIBX_LD_FLAGS)
