x86_ptable ?= mbr

x86_ext_cx16 ?= supported
x86_ext_x2apic ?= supported
x86_ext_movbe ?= supported
x86_ext_popcnt ?= supported
x86_ext_aes ?= supported
x86_ext_avx ?= supported
x86_ext_fpu ?= supported
x86_ext_vme ?= supported
x86_ext_pse ?= supported
x86_ext_tsc ?= supported
x86_ext_pae ?= supported
x86_ext_mce ?= supported
x86_ext_cx8 ?= supported
x86_ext_apic ?= supported
x86_ext_sep ?= supported
x86_ext_pge ?= supported
x86_ext_pat ?= supported
x86_ext_pse36 ?= supported
x86_ext_psn ?= supported
x86_ext_clfl ?= supported
x86_ext_acpi ?= supported
x86_ext_mmx ?= supported
x86_ext_sse ?= supported
x86_ext_sse2 ?= supported
x86_ext_nx ?= supported
x86_ext_lm ?= supported

.PHONY: all clean

all: .

clean: .
