AUTO_OBJECTS += $(X86_BOOT)/header.bin
AUTO_OBJECTS += $(X86_BOOT)/boot.bin
AUTO_OBJECTS += $(X86_BOOT)/a20.bin
AUTO_OBJECTS += $(X86_BOOT)/nmi.bin
AUTO_OBJECTS += $(X86_BOOT)/gdt.bin
AUTO_OBJECTS += $(X86_BOOT)/pm.bin
