PLATFORM_PATH := ../..
PLATFORM_X86_PATH := $(PLATFORM_PATH)/x86
PLATFORM_X86_BOOT_PATH := $(PLATFORM_X86_PATH)/boot
PLATFORM_X86_INCLUDE_PATH := $(PLATFORM_X86_PATH)/include
PLATFORM_X86_KERNEL_PATH := $(PLATFORM_X86_PATH)/kernel
