PLATFORM := ../..
PLATFORM_X86 := $(PLATFORM)/x86
PLATFORM_X86_BOOT := $(PLATFORM_X86)/boot
PLATFORM_X86_INCLUDE := $(PLATFORM_X86)/include
PLATFORM_X86_INJECTOR := $(PLATFORM_X86)/injector
PLATFORM_X86_KERNEL := $(PLATFORM_X86)/kernel
