STAGE0_NAME := stage0
STAGE0_PATH := .
STAGE0_ASFLAGS := -D STAGE0_DEFINED -f bin
STAGE0_OBJECT = $(STAGE0_PATH)/start.nasm
STAGE0_OUTPUT := $(STAGE0_PATH)/$(STAGE0_NAME).img

ASFLAGS += $(STAGE0_ASFLAGS)
OBJECT += $(STAGE0_OBJECT)
