DEBUG_PARENT_NAMESPACE ?=
DEBUG_NAME ?= "unknown"
ifeq ($(DEBUG_PARENT_NAMESPACE),)
DEBUG_NAMESPACE = "("$(DEBUG_NAME)")"
else
DEBUG_NAMESPACE = $(DEBUG_PARENT_NAMESPACE)" -> ("$(DEBUG_NAME)")"
endif
DEBUG_PREFIX = $(DEBUG_NAMESPACE)"::"
DEBUG_FLAGS = --no-print-directory DEBUG_PARENT_NAMESPACE=\"$(DEBUG_NAMESPACE)\"
