PATTERN_NASM_SOURCE_EXTENSION := .nasm
PATTERN_NASM_OBJECT_EXTENSION := .bin
PATTERN_C_SOURCE_EXTENSION := .c
PATTERN_C_OBJECT_EXTENSION := .o

PATTERN_NASM_SOURCE := *$(PATTERN_NASM_SOURCE_EXTENSION)
PATTERN_NASM_OBJECT := *$(PATTERN_NASM_OBJECT_EXTENSION)
PATTERN_C_SOURCE := *$(PATTERN_C_SOURCE_EXTENSION)
PATTERN_C_OBJECT := *$(PATTERN_C_OBJECT_EXTENSION)
