cmake_minimum_required(VERSION 3.22)

set(CMAKE_ASM_FLAGS "")

#list(APPEND CMAKE_FIND_ROOT_PATH "")
#set(CMAKE_FIND_ROOT_PATH /usr/i586-mingw32msvc /home/alex/mingw-install)

#set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

#set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)