ROOT ?= ../..
SHARED ?= $(ROOT)/shared

SHARED_LIBX ?= $(SHARED)/libx
include $(SHARED_LIBX)/library.mk

include $(SHARED)/make/object.mk
SHARED_LIBK ?= $(SHARED)/libk
SHARED_LIBK_INCLUDE ?= $(SHARED_LIBK)/include
SHARED_LIBK_NASM_FLAGS ?= -i $(SHARED_LIBK_INCLUDE) $(SHARED_LIBX_NASM_FLAGS)
SHARED_LIBK_NASM_OBJECTS ?= $(call object_prepare_nasm,$(SHARED_LIBK_INCLUDE),$(SHARED_LIBX_NASM_OBJECTS))
SHARED_LIBK_GCC_FLAGS ?= -I $(SHARED_LIBK_INCLUDE) $(SHARED_LIBX_GCC_FLAGS)
SHARED_LIBK_C_OBJECTS ?= $(call object_prepare_c,$(SHARED_LIBK_INCLUDE),$(SHARED_LIBX_C_OBJECTS))
SHARED_LIBK_LD_FLAGS ?= $(SHARED_LIBX_LD_FLAGS)
