ROOT ?= ../../..
ARCH ?= $(ROOT)/arch
X86 ?= $(ARCH)/x86
SHARED ?= $(ROOT)/shared

X86_LIBEFI ?= $(X86)/libefi
include $(X86_LIBEFI)/library.mk

SHARED_BOOTEFI ?= $(SHARED)/bootefi
include $(SHARED_BOOTEFI)/library.mk

include $(SHARED)/make/object.mk
X86_BOOTEFI ?= $(X86)/bootefi
X86_BOOTEFI_IMAGE ?= $(X86_BOOTEFI)/bootefi.img
X86_BOOTEFI_INCLUDE ?= $(X86_BOOTEFI)/include
X86_BOOTEFI_NASM_FLAGS ?= -f elf32 -D BITS32 -i $(X86_BOOTEFI_INCLUDE) $(X86_LIBEFI_NASM_FLAGS) $(SHARED_BOOTEFI_NASM_FLAGS)
X86_BOOTEFI_NASM_OBJECTS ?= $(call object_prepare_nasm,$(X86_BOOTEFI_INCLUDE),$(X86_LIBEFI_NASM_OBJECTS) $(SHARED_BOOTEFI_NASM_OBJECTS))
X86_BOOTEFI_GCC_FLAGS ?= -std=gnu99 -Werror -O0 -nostdinc -ffreestanding -m32 -D BITS32 -c -I $(X86_BOOTEFI_INCLUDE) $(X86_LIBEFI_GCC_FLAGS) $(SHARED_BOOTEFI_GCC_FLAGS)
X86_BOOTEFI_C_OBJECTS ?= $(call object_prepare_c,$(X86_BOOTEFI_INCLUDE),$(X86_LIBEFI_C_OBJECTS) $(SHARED_BOOTEFI_C_OBJECTS))
X86_BOOTEFI_LD_FLAGS ?= -T $(X86_BOOTEFI)/script.ld -nostdlib $(X86_LIBEFI_LD_FLAGS) $(SHARED_BOOTEFI_LD_FLAGS)
X86_BOOTEFI_LD_OBJECTS ?= $(X86_BOOTEFI_NASM_OBJECTS) $(X86_BOOTEFI_C_OBJECTS)

include $(X86)/make/toolchain.mk

X86_BOOTEFI_INDEX ?= $(X86_BOOTEFI)/compile_commands.json
