SHARED_NAME := shared
SHARED_PATH := $(ARCH_X86_PATH)/$(SHARED_NAME)
SHARED_ASFLAGS := -D ARCH_X86_DEFINED -D SHARED_DEFINED -I $(SHARED_PATH)
SHARED_CFLAGS := -D ARCH_X86_DEFINED -D SHARED_DEFINED -I $(SHARED_PATH)
SHARED_LDFLAGS :=
SHARED_OBJECTS = $(patsubst %.S, %.bin, $(wildcard $(SHARED_PATH)/*.S)) \
                 $(patsubst %.c, %.o, $(wildcard $(SHARED_PATH)/*.c))

ASFLAGS += $(SHARED_ASFLAGS)
CFLAGS += $(SHARED_CFLAGS)
LDFLAGS += $(SHARED_LDFLAGS)
OBJECTS += $(SHARED_OBJECTS)
