ROOT ?= ../..
SHARED ?= $(ROOT)/shared

include $(SHARED)/make/object.mk
SHARED_LIBX ?= $(SHARED)/libx
SHARED_LIBX_INCLUDE ?= $(SHARED_LIBX)/include
SHARED_LIBX_NASM_FLAGS ?= -i $(SHARED_LIBX_INCLUDE)
SHARED_LIBX_NASM_OBJECTS ?= $(call object_find_nasm,$(SHARED_LIBX_INCLUDE))
SHARED_LIBX_GCC_FLAGS ?= -I $(SHARED_LIBX_INCLUDE)
SHARED_LIBX_C_OBJECTS ?= $(call object_find_c,$(SHARED_LIBX_INCLUDE))
SHARED_LIBX_LD_FLAGS ?=
