ROOT ?= ../..
SHARED ?= $(ROOT)/shared

SHARED_LIBX ?= $(SHARED)/libx
include $(SHARED_LIBX)/library.mk

include $(SHARED)/make/object.mk
SHARED_LIBEFI ?= $(SHARED)/libefi
SHARED_LIBEFI_INCLUDE ?= $(SHARED_LIBEFI)/include
SHARED_LIBEFI_NASM_FLAGS ?= -i $(SHARED_LIBEFI_INCLUDE) $(SHARED_LIBX_NASM_FLAGS)
SHARED_LIBEFI_NASM_OBJECTS ?= $(call object_prepare_nasm,$(SHARED_LIBEFI_INCLUDE),$(SHARED_LIBX_NASM_OBJECTS))
SHARED_LIBEFI_GCC_FLAGS ?= -I $(SHARED_LIBEFI_INCLUDE) $(SHARED_LIBX_GCC_FLAGS)
SHARED_LIBEFI_C_OBJECTS ?= $(call object_prepare_c,$(SHARED_LIBEFI_INCLUDE),$(SHARED_LIBX_C_OBJECTS))
SHARED_LIBEFI_LD_FLAGS ?= $(SHARED_LIBX_LD_FLAGS)
