set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_VERSION 1.0.0-alpha)
set(CMAKE_SYSTEM_PROCESSOR i686)

set(CMAKE_ASM_COMPILER nasm)
set(CMAKE_C_COMPILER i686-elf-gcc)
set(CMAKE_CXX_COMPILER i686-elf-g++)

#list(APPEND CMAKE_FIND_ROOT_PATH "")
#set(CMAKE_FIND_ROOT_PATH /usr/i586-mingw32msvc /home/alex/mingw-install)

#set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

#set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
#set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)